# Generated by Django 3.1.2 on 2021-04-13 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210413_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_id', models.ManyToManyField(related_name='Followings', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ManyToManyField(related_name='Followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
