# Generated by Django 3.1.2 on 2021-04-13 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210413_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='user_id',
            new_name='follower_id',
        ),
        migrations.RemoveField(
            model_name='following',
            name='following_id',
        ),
        migrations.AddField(
            model_name='following',
            name='followed_id',
            field=models.ManyToManyField(related_name='followeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
